### ISSUE TITLE
x509pop server plugin regex

### ISSUE THREAD

**Issue by kfox1111** [spiffe/spire#4774] opened 2024-01-04 16:46 UTC
Say you have an x509pop server. It issues many different certs. You wish to reuse this for node attestation. But you don't want just any cert issued by the CA to be able to register with your spire, but a restricted set.

It would be nice if there was a way to give the x509pop server a list of regexes to validate the post rendered agent_path_template value against when registering the node. If it doesn't match any regex in the list, the node registration would be denied.

**Comment by evan2645** [comment] 2024-01-16 18:54
Hi @kfox1111!

> Say you have an x509pop server. It issues many different certs. You wish to reuse this for node attestation. But you don't want just any cert issued by the CA to be able to register with your spire, but a restricted set.

Why just a restricted set? What qualifies a cert to be from this set or not?

**Comment by kfox1111** [comment] 2024-01-16 21:14
For example, say you have letsencrypt certs for things. you don't trust the entire letsencrypt ca to bind to your spire. or you have your own local organizational ca that issues certs, and you might want to trade one of those to bootstrap your spire. You might not want every cert in the org to be able to trade for a spire identity.

The regex list would be what sets if they can join or not. If it matches a pattern, its ok. If it fails to match any pattern, its denied?

**Comment by kfox1111** [comment] 2024-01-17 10:22
Maybe a more concrete example.

Say you have a couple clusters of nodes `n[0-8].example.org` and `s[0-3].example.org` that you want to allow registering, but not allow other certs in the same domain, or other domains.

**Comment by evan2645** [comment] 2024-02-06 20:09
Thanks @kfox1111 - I understand what you're asking for, more just trying to understand why 😅 

> For example, say you have letsencrypt certs for things. you don't trust the entire letsencrypt ca to bind to your spire. or you have your own local organizational ca that issues certs, and you might want to trade one of those to bootstrap your spire. You might not want every cert in the org to be able to trade for a spire identity.

This explanation leads me to believe that this could be supported by e.g. designating an intermediate that we want to trust for this purpose.

> Say you have a couple clusters of nodes n[0-8].example.org and s[0-3].example.org that you want to allow registering, but not allow other certs in the same domain, or other domains.

This would presumably not be solved by designating one or more trustworthy intermediates, but I understand the desire to do it less than the first. Or would requiring a certain intermediate also solve this case for you?

**Comment by kfox1111** [comment] 2024-02-06 21:09
The regex would be easier to use then an intermediary I think. For my specific use case I have in mind, getting a cert for a machine in an org would be relatively easy. I don't know of any acme implementation that allows filtering. Proving the host was part of a subset to make an intermediate would require the same kind of regex pattern matching that is proposed for inclusion here I think? Just extra steps involved.

**Comment by evan2645** [comment] 2024-02-29 19:02
Would solving https://github.com/spiffe/spire/issues/4788 lessen the need for this feature?

It would be better to match regex against some property in the cert than against a post-rendered agent_path_template. That raises questions around what exactly we're matching and how. In general, just feels like a feature that's going to be hard to get right, which is why I'm asking so many questions

**Comment by kfox1111** [comment] 2024-02-29 19:07
Yeah, probably. Though still may be useful here. And maybe some of the code can be shared between the two.

Maybe instead of the rendered agent_path_template, the entry could be validated against the cn of the cert? Would that simplify things?

**Comment by evan2645** [comment] 2024-04-25 19:25
@kfox1111 since we'll have some regex matching features in the new http_challenge node attestor, is it ok to close this out for now? Or you need more than that?

**Comment by kfox1111** [comment] 2024-04-25 19:50
I think I'll be using the http_challenge plugin rather then this one, so my need would go away. It may be an issue we could keep around as an easy new contributor drive by feature. The http_challenge already has the logic implemented and would be fairly easy then to lift into other plugins I think.

**Comment by azdagron** [comment] 2024-04-30 18:46
We'll go ahead and close this out for now.

**Closed by azdagron** 2024-04-30 18:46 UTC
Labels: triage/in-progress
