### ISSUE TITLE
Rebootstrap

### ISSUE THREAD

**Issue by kfox1111** [spiffe/spire#5585] opened 2024-10-16 16:28 UTC
If the agent's trust bundle expires, it does not seem to attempt to reattest using the bootstrap trust bundle/url.

It would be good if it could, so that those with large setups could more easily recover from a failure.

**Comment by sorindumitru** [comment] 2024-10-17 07:16
This seems to be a duplicate of https://github.com/spiffe/spire/issues/4624

**Closed** 2024-10-17 13:35 UTC
