### ISSUE TITLE
SPIRE Agent with a valid and not expired SVID can not be restarted

### ISSUE THREAD

**Issue by dnkolegov** [spiffe/spire#842] opened 2019-04-09 08:11 UTC
* **Version**: 0.7.3
* **Platform**: `Linux kali 4.14.0-kali1-amd64 #1 SMP Debian 4.14.2-1kali1 (2017-12-04) x86_64 GNU/Linux`
* **Subsystem**: jointoken

A SPIRE agent attested using `jointoken` can not be restarted despite that its SVID is valid and not expired.

## Steps to reproduce:
1.  Deploy SPIRE server and agent following the instructions in the `Getting started` section.
Use the default configs and certificates.

2.  Run the server:
```
spire-server run  -config /opt/spire/conf/server/server.conf
```
Generate a join token:
```
spire-server token generate -spiffeID spiffe://example.org/host
```

3. Run the agent:
Configure keymanager plugin as "disk" n `agent.conf`
```
spire-agent run \
    -config /opt/spire/conf/agent/agent.conf \
    -joinToken {your previously generated token}
```
The agent will have been started. Then stop the agent using `Ctrl-C`.

Run the command to start the agent again:

```
spire-agent run -config /opt/spire/conf/agent/agent.conf
```

The result is as follows:

```
root@kali:~# spire-agent run     -config /opt/spire/conf/agent/agent.conf
WARN[0000] Current umask 0022 is too permissive; setting umask 0027. 
INFO[0000] data directory: "/opt/spire/.data"           
INFO[0000] Starting plugin catalog                       subsystem_name=catalog
DEBU[0000] NodeAttestor(join_token): configuring plugin  subsystem_name=catalog
DEBU[0000] KeyManager(disk): configuring plugin          subsystem_name=catalog
DEBU[0000] WorkloadAttestor(k8s): configuring plugin     subsystem_name=catalog
DEBU[0000] WorkloadAttestor(unix): configuring plugin    subsystem_name=catalog
DEBU[0000] WorkloadAttestor(docker): configuring plugin  subsystem_name=catalog
INFO[0000] Stopping plugin catalog                       subsystem_name=catalog
2019/04/09 21:06:02 [DEBUG] plugin: waiting for all plugin processes to complete...
ERRO[0000] agent crashed: receiving attestation data: Join token attestation attempted but no token provided 
```

**Comment by marcosy** [comment] 2019-04-09 12:07
Hello @dnkolegov! Thanks for reporting this. A similar issue (#809) was filed some days ago for AWS attestor. The root cause seems to be the same in both cases.

There is already a PR opened (#839), once it gets merged, both issues should be solved.

**Comment by azdagron** [comment] 2019-04-09 12:33
The checked in agent.conf defaults to the memory KeyManager, which does not persist the private key for the agent SVID. You need to switch to the disk KeyManager if you want the agent private key persisted between restarts.

**Comment by dnkolegov** [comment] 2019-04-09 13:20
The original bug was reproduced with disk key manager.
Sorry for misunderstanding.

Regards,
Denis Kolegov.

вт, 9 апр. 2019 г., 19:33 Andrew Harding <notifications@github.com>:

**Closed** 2019-04-11 21:10 UTC
