### ISSUE TITLE
Delegated Identity API reaches gRPC size limit on large deployment

### ISSUE THREAD

**Issue by meyskens** [spiffe/spire#3965] opened 2023-03-10 12:42 UTC
When using the Delegated Identity API on a large deployment where it has to watch many identities (tested in 10 000+) the cache update call that sends a "state of the world" update quickly hits the 4MB maximum for a message in gRPC. This will cause errors in the update calls and depending on how the application handles it it will either stop receiving updates or panic. 

## Proposed solutions

1. Make the API calls paginated, from what I understand something similar had already been implemented elsewhere in SPIRE 
2. Make a delta only API that only sends the updates instead of the state of the world (mechanics like a Kubernetes watcher?)
3. Something else? 

## Workaround
This can be worked around via setting the message limit to something  higher than 4MB, like 20MB. However this doesn't scale and is far from ideal to rely on in a production scenario.
```go
grpc.WithDefaultCallOptions(
			grpc.MaxCallRecvMsgSize(20*1024*1024),
			grpc.MaxCallSendMsgSize(20*1024*1024))) 
```

**Comment by evan2645** [comment] 2023-03-28 13:59
Hey @meyskens , thank you for opening this and your patience as well

We're wondering what kind of conditions are causing you to run into this .. generally speaking, the delegated identity API is meant to turn on one stream per workload, and it is surprising that a single workload would have 10k+ identities.

Not sure if you're running k8s or not, but similarly, k8s limits the number of [pods per node](https://kubernetes.io/docs/setup/best-practices/cluster-large/) to 110. Can you help us to understand the conditions that lead to 10k+ identities being managed on a single node? There are probably concerns there beyond just delegated identity API (e.g. SPIRE Agent SVID caching behaviors).

**Comment by edwbuck** [comment] 2023-04-07 18:35
I can comment on a similar gRPC size limit, in a K8s cluster.  We had a large number of SPIRE entries configured to match on selectors that didn't include the node Identity.  As a result, these SPIRE entries were download to all nodes, should a Pod containing a matching workload be launched on the node.  This shifted the number of entries from limits that applied to a node to limits that applied to an entire k8s cluster.

We discovered the issues, adjusted our SPIRE entries, and reduced the entry per node count.  With that in mind, the impact of overflowing the gRPC size limit was severe.  Effectively we watched all Agents get stuck in restart loops, and no Agent could service a Workload.

I would recommend that we implement some sort of paging system too; but, I would also recommend we avoid the paging approaches of the past (where a single query has a number of pages, structured by row count).  

Instead we should structure the "return a list of items" RPCs to return items in their object identifier order, and update the calls to resemble `query(starting_id, limit)` semantics.  This technique leverages the B-trees of databases for optimal throughput, is compatible with most caching systems, and requires no new need to keep query contexts open to track row counts.  The RPC client would then be responsible for counting the returned list of items, and if it equals the limit, issuing a new query starting at the last known (or last known + 1) identifier.

Ideally a new datadog metric of "entries" in the agents would also be exposed, so people could easily visualize if their setup should warrant attention because of excessive entries per node.

**Comment by youngnick** [comment] 2023-04-25 11:42
For the original query, we're likely to run across the limits more quickly than others because we're basically delegating the last-mile of the attestation process to the Cilium agent, instead of the SPIRE agent.

I'll explain. 

We're using SPIFFE and SPIRE to transparently do mTLS _on behalf of_ workloads running in the cluster. In Cilium, we already have the concept of a Cilium Identity, which is created when Cilium detects a new workload (set of pods with the same set of labels). When a new Cilium identitiy is created, it's assigned an integer and then an operator talks to the SPIRE server (across the network, using an assigned-admin SPIFFE ID that's granted to the Cilium operator), and adds a new SPIFFE identity that looks like `spiffe://trust.domain/identity/<integer>`. The selector on this is a custom cilium-specific one rather than using a Kubernetes one.

When the Cilium agent is running, it uses the DelegatedIdentity API to watch _all_ identities in the cluster (using the custom Cilium-specific selector), and then it filters the identities it needs afterwards. (We don't know when creating the identitiy which nodes it will run on, so we can't easily encode the Node identity in there to make it possible for the Cilium agent to set up a smaller watch).

Because of all of this, the total number of identities that Cilium is watching will be correlated to the number of distinct sets of pods running in a cluster, rather than the number of pods running on a single node.

There's a lot in this explanation, so please feel free to ask here or ping me in #cilium on SPIRE slack (I'm youngnick there as well).

**Comment by evan2645** [comment] 2023-05-10 17:30
Thanks for the thorough explanation @youngnick 

The current shape of the delegated identity api wasn't designed for this kind of usage. We actually designed and shipped that API specifically to support the cilium integration, and we had [many](https://github.com/spiffe/spire/issues/2246) [long](https://github.com/spiffe/spire-api-sdk/issues/4) [conversations](https://github.com/spiffe/spire-api-sdk/pull/7) [about](https://github.com/spiffe/spire-api-sdk/pull/8) how it could/should work, so I have to admit I'm a little surprised to hear all this 😅

The SPIRE threat model assumes that nodes/agents can be compromised, so in general, the project (fairly strongly) tries to lean away from patterns that involve all nodes getting all identities. If that were the case, then a single node compromise immediately translates into cluster compromise. Ideally, registrations are made based on scheduler placements similar to the way that the [spire-controller-manager](https://github.com/spiffe/spire-controller-manager) does it.

> When the Cilium agent is running, it uses the DelegatedIdentity API to watch all identities in the cluster (using the custom Cilium-specific selector), and then it filters the identities it needs afterwards. (We don't know when creating the identitiy which nodes it will run on, so we can't easily encode the Node identity in there to make it possible for the Cilium agent to set up a smaller watch).

I'm not sure I completely follow this, but if the Cilium agent is able to filter and apply the correct identities to the correct flows, shouldn't it also know what identities it needs, and thus be in a position to ask only for what's needed? As you may read in the above-linked discussions, the stream is designed to be subscribed to on per-workload basis, where in this case, the workload is the software that Cilium agent is acting on behalf of (and not Cilium agent itself).

Since we're discussing a different usage than was intended, I don't feel it's appropriate to make changes to the existing RPC(s) to support the new use case. It would be better to introduce new RPCs that directly support it ... that said, the use case itself seems to go against the grain a bit, so IMO it's probably worth some additional discussion/scrutiny to see if there are any other approaches that are more well aligned with the needs and philosophies of both projects

**Comment by youngnick** [comment] 2023-05-24 11:18
Sorry to take a while to get back to you here @evan2645.

We've ended up using a different design to the original proposal for integrating SPIFFE and SPIRE into Cilium - the original proposal would have added a label, and in this implementation, Cilium's operator is creating and managing the identities itself.

The intent here is to make the SPIFFE identity use _transparent_, so that the Pods don't even know they are being authenticated. In other service meshes, this can be handled by having the sidecar proxy (which is part of the pod as far as the Workload API is concerned) reach out and get the identity, and then use that.

For our implementation, the Cilium agent is watching the pods (This is the same as before), but the operator is creating the SPIFFE entries in the SPIRE server.

When the operator creates the entries, it creates them with its own selectors that include the Cilium ID ( an integer) that is used by the BPF datapath to filter traffic, and which has a 1:1 correspondence with a set of Kubernetes labels.

When this entry is created, we don't actually _know_ which nodes the pods will run on, because the Identity is created before the pods start up (it actually blocks pod startup until the Identity is ready). So we can't easily put a node selector on there - the information isn't available when the identity is created. This Identity is persisted to a CRD - which stores the numeric identity -> pod labels mapping.

So, I'm not sure in this case how best to add information to the SPIRE entry to encode _which_ identities belong to the agent's node. Normally, the Workload API handles this because the SPIRE agent can see which Pod is asking, and each Pod can only belong to one identity.

However, because the Cilium agent _must_ at least see all the identities that have pods running on the same node as it, I don't see a way to have it only request relevant identities - we are essentially delegating the last mile of attestation to the Cilium agent, and relying on it to not use identities that are not relevant. I understand that this puts it in essentially the same category as the SPIRE _server_ rather than the SPIRE _agent_, which I acknowledge is not ideal, but this was the only way I could get things to work. 

I also considered having the agent filter the identities it gets to only the ones with pods running, throwing away the rest, but that means that,  when pods start up, they will be unable to do authentication until the next update from the DelegatedIdentity API (or we would need to re-get on every Pod startup).

Another option I considered was having the Operator add per-node-selector fields to each node a Pod is scheduled to, but because the DelegatedIdentity API watch is called with a set of selectors, and the only entries shown must have _all_ of their fields match a subset of the selectors, we can't add selectors to cover it.

That is, we currently add a SPIRE entry with a selector like this:
```
cilium:mutual
```
then, we just have the call to the DelegatedIdentity API watch only that selector.

From my testing, it seems that if we add selectors like this:
```
cilium:mutual
cilium:nodeid:node1
cilium:nodeid:node2
```
Then we can't have the agent on node1 watch, because it will need to watch for identities that look like:
```
cilium:mutual
cilium:nodeid:node1
```
And that doesn't match the whole set of selectors on the entry.

Aside from all that, this will add a big eventual-consistency timeout to the whole process - and we are considering holding pod startup until the full set of handshakes are completed in the future as well.

I totally get what you're saying about unintended usage, and I'd like to try and get to a point where we're both happy. But this is where we've ended up as of today, with a scalability problem. Sigh. Interested in any thoughts you have here.

**Comment by evan2645** [comment] 2023-06-01 18:17
> Sorry to take a while to get back to you here @evan2645.

No worries .. these kinds of issues always take a while to digest and turn around, for myself included

> So, I'm not sure in this case how best to add information to the SPIRE entry to encode which identities belong to the agent's node.

I think there are two parts to the problem here ... the first is the more tactical and acute issue of, Cilium agent is subscribing to all workloads over the same DelegatedIdentity stream. The second is the cluster-wide registration issue. The former is what you're bumping into in this issue (but I believe SPIRE will internally handle the circumstance well), and the latter is more of a "hey just want to point out the security implications of registering workloads cluster-wide" and "we generally try to not encourage that".

I think we can probably find a quick solution to the first one. Solving the second one will take further consideration. If the Cilium threat model does not consider or account for node compromise, then it might not be worth tackling. If it does, then you'll probably want to reach for a new/different kind of controller

> However, because the Cilium agent must at least see all the identities that have pods running on the same node as it, I don't see a way to have it only request relevant identities - we are essentially delegating the last mile of attestation to the Cilium agent, and relying on it to not use identities that are not relevant.

What I meant here was that Cilium agent can get a big bag of SVIDs to use for the workloads it's serving, but in the end it still needs to know which of those SVIDs should be applied to which workloads. This part of your response caught my attention:
```
This Identity is persisted to a CRD - which stores the numeric identity -> pod labels mapping.
```

So I assume that Cilium agent looks up these CRDs in order to determine which Cilium IDs apply to which pods? If this is the case, then one approach could be to perform this lookup first, obtain the Cilium ID for the pod in question ... then call the DelegatedIdentity API with this Cilium ID. At that point, you'd have a selector like `cilium:id:X`. The Cilium agent is "attesting" that the workload has Cilium ID X, and then calls SPIRE Agent with it. Then you get one stream per pod/workload, which was the original intended usage

There's a lot of moving parts in this issue, as you know ... it can be hard to discuss just in this thread. I recommend stopping by the [SIG-SPIRE](https://github.com/spiffe/spiffe/blob/main/community/sig-spire/README.md#sig-spire-1) recurring call, which will happen next Thursday the 8th at 10:30am Pacific time.

**Comment by evan2645** [comment] 2023-06-08 18:32
Hey @youngnick and @meyskens, just wanted to check in here to see if this is making sense, if we can find a path forward, etc. Missed you all on the SIG-SPIRE call today, but happy to help arrange time for you on the next call (2 weeks from now) if it's something you're interested in.

**Comment by evan2645** [comment] 2023-06-13 19:02
Hi again @youngnick and @meyskens - not sure if you want to continue down this path or not ... we're going to close this issue out for now, please ping us in Slack, this or a new issue, or SIG-SPIRE if you'd like to continue the discussion. Definitely interested in finding a mutually agreeable solution ❤️

**Closed by evan2645** 2023-06-13 19:02 UTC
Labels: triage/in-progress

**Comment by youngnick** [comment] 2023-06-14 11:59
Yeah, sorry to not be coming back sooner here, fair enough about closing the issue. We're finishing up the code for this for now, and it the current version will be in Cilium 1.14 - I'd like to come and talk some more once we've got the heavy lifting for the release done.

**Comment by evan2645** [comment] 2023-06-22 18:21
No worries @youngnick , we'd love to continue the conversation! Please just let us know when you're ready and I can help facilitate. Probably best to ping back in slack, a new issue, or you can show up to a [SIG-SPIRE](https://github.com/spiffe/spiffe/blob/main/community/sig-spire/README.md) and we can chat there ... a comment on a closed issue might get missed 😓 looking forward to it!
