### ISSUE TITLE
Metrics are only emitted few seconds on Prometheus

### ISSUE THREAD

**Issue by inajob** [spiffe/spire#2206] opened 2021-04-12 05:47 UTC
I noticed all metrics are deleted after few seconds on Prometheus.
The cause is go-metics default expiration. https://github.com/armon/go-metrics/blob/8ca742bd545671bedae063d0672cb3c8da7d4437/prometheus/prometheus.go#L23

It is good for reducing metrics, but I think this feature should only activate for some specific time series.

For example, I want to collect the version of SPIRE server.
`spire_server_started` seems to bo good metric for this purpose, but this metric only emits for few seconds after server started.

I think this is not expected behavior, and not only `spire_server_started` but almost all metrics should be emitted forever.

* **Version**: 0.12.0
* **Platform**: collect metrics from Prometheus 2.23.0
* **Subsystem**: -

**Comment by rturner3** [comment] 2021-04-21 21:48
Hi @inajob , thanks for reporting this. I don't see any use cases as of now for stopping reporting of a stat, so changing the default behavior of the Prometheus metrics sink to not expire metrics makes sense to me.

I can push a quick PR for this.

**Comment by rturner3** [comment] 2021-04-22 19:46
Hey @inajob , before trying to change this default behavior, I wanted to understand a bit more what kinds of issues you're running into when the metrics are not emitted during every reporting cycle.

Also is this behavior problematic in your consumption of all metrics or just gauges like `spire_server_started`? I see that the metrics expiration configuration in `armon/go-metrics` is something that applies to all metric types. If the issue is specific to gauges, we may be able to work around this by periodically emitting the gauge values in SPIRE.

I am not as familiar about whether this metrics "expiration" behavior is a normal producer pattern for Prometheus, so if you have more experience using Prometheus, I would appreciate your input.

**Comment by inajob** [comment] 2021-04-23 03:04
Thank you for PR!

I think it is not only the gauge values problem. It seems to be ok that you let expiration of all metric type forever.

---

I noteiced below two problems, but it seems to be less impact than expiration of metrics.

In case of metric that has various labels, this change may cause combinatorial explosion problem.
But according to [this telemetry document](https://github.com/spiffe/spire/blob/main/doc/telemetry.md), there seems to be no metrics which cause problem.

And this change affects the behavior of count type metrics. Before this change, count type metrics reset every expiration. But after this change, these accumulate even if there are no events.

**Comment by jalev** [comment] 2021-04-26 11:37
I would argue only to only consider expiring things if people start complaining about it. Too much telemetry is better than spotty telemetry. 

I'll mirror what @inajob in that there doesn't appear to be any super-cardinal metrics being exposed by Spire at the moment. Spire produces very few unique metrics even at small/medium scale (we run about 280 agents in our Production Kubernetes clusters, for example). Even for the ones which are _slightly_ more cardinal than usual (e.g. agent manager sync fetch entries) they don't end up with a lot of metrics (see image below), and even if they did, I'd fix this at the Prometheus side first (writing Recording Rules for precomputing) rather than Spire.

![Screenshot 2021-04-26 at 12 08 28](https://user-images.githubusercontent.com/1196058/116076041-a1ca8080-a68b-11eb-979a-99e469ed0b27.png)

**Comment by rturner3** [comment] 2021-04-27 20:08
Thanks for the feedback. I think this should be addressed by #2239.

**Closed by rturner3** 2021-04-27 20:08 UTC
