### ISSUE TITLE
Add "nonRoot" selector to unix WorkloadAttestor

### ISSUE THREAD

**Issue by udf2457** [spiffe/spire#4036] opened 2023-03-31 13:00 UTC
At present, with the `unix` WorkloadAttestor, if you want to constrain to a user, you need to explicitly set that user via `unix:uid`.

For many workloads, it might be more useful to ensure a workload is not running as root, therefore being able to set a simple `nonRoot` selector to ensure `workload.uid != 0` would be very useful, so perhaps a simple boolean `unix:nonRoot` ?

**Comment by edwbuck** [comment] 2023-04-07 16:05
It seems to me that the main request is more of a selector that includes non-equality operations, like not equals.  That this selector is focused around the root user id is just an example of when this might be used.

The alteration of the core operating system to accommodate a "I'm not root group" is just a side-bar suggestion, and one that any root user / root process can easily ignore (as root can override enforcement), so let's take it out of the issue.

**Comment by udf2457** [comment] 2023-04-07 19:53
I think that's a fair summary of my concept @edwbuck. 

As you say, anything that is root (or can gain root equivalent) can override any constraints anyway.

However having to manually define non-root selectors as suggested @amartinezfayo is too workload intensive for the sysadmin because there are so many ways "non-root" can be defined (both directly, and indirectly, e.g via `systemd` `DynamicUser=yes`)

Hence my suggestion for the more abstract `nonRoot` check at WorkloadAttestor level.

But as you say "nonRoot" could perhaps be better called `!= thisUser` if it sits better in your thinking.

Hope this makes sense ?

**Comment by edwbuck** [comment] 2023-04-10 14:48
I like the != some user better than != root, as old-time unix tricks can effectively make other user names have root-equivalent permissions.

**Comment by udf2457** [comment] 2023-04-11 08:02
Thinking aloud, if we're going down the != some user track, then maybe != some (e)uid is also needed, that way a !=0 check can be done to pick up effective root scenarios (or maybe do it more smartly in the background, so if someone specifies "root" in a != some user check, that also includes a (e)uid=0 check).

**Comment by edwbuck** [comment] 2023-04-11 15:18
checking the uid seems wrong, the effective user id is the user that's running the program.

**Comment by amartinezfayo** [comment] 2023-04-13 14:34
This non-equality operation is like asserting the absence of a selector (e.g. having a condition user != foo is like asserting the absence of `unix:user:foo`). When a selector is emitted by a workload attestor after asserting that it's true, there is a high level of confidence, but the same cannot be said for the absence of a selector, because the absence can be caused by a failure in the attestor due to a variety of reasons like misconfiguration, timeout, etc.
Introducing selector negation is problematic because current behavior is to do best-effort attestation. Workload attestors can return errors, but SPIRE still collects the selectors from other attestors and attempts to match the workload to an identity.
We have analyzed this in the past, and proving a negative condition can be tricky and we haven't figured out a clear path towards supporting this.

**Comment by amartinezfayo** [comment] 2023-04-25 18:29
Closing this, as we don't have a clear path towards supporting this. Please reopen if you think that further discussion is needed.

**Closed by amartinezfayo** 2023-04-25 18:29 UTC
Labels: triage/in-progress
