### ISSUE TITLE
Add support for multiple platforms to the docker images

### ISSUE THREAD

**Issue by marcofranssen** [spiffe/spire#3542] opened 2022-10-28 11:25 UTC
* **Version**: 1.4.4
* **Platform**: EKS Bottlerocket (arm64v8)
* **Subsystem**: all components

To support Spire on my EKS cluster arm64v8 nodes it would be great if the Spire images would support various platforms. Especially for the spire-agent this is highly appreciated so also my arm64 deployments running on arm64 nodes can use spiffe ids issued by a spire-agent on the arm64 nodes.

Currently when trying to deploy on the arm64 nodes we see following error.

```shell
exec /usr/bin/dumb-init: exec format error
```

This does make sense as the image wasn't build for this architecture.

I temporarely resolved this by adding a nodeSelector to my deployments.

```yaml
nodeSelector:
  kubernetes.io/arch: amd64
```

However this means all my arm64 nodes and deployments can't issue spiffe-ids as those nodes do not run a spire-agent.

**Comment by azdagron** [comment] 2022-10-28 15:11
Thanks for opening this, @marcofranssen. This is a duplicate of #1984. In short, we're totally on board with providing multi-arch images. It has not been high priority for the maintainers to pick up directly though, so if folks want it sooner than later, a contribution would be more than welcome.

**Closed by azdagron** 2022-10-28 15:11 UTC
