### ISSUE TITLE
SPIRE Server allows duplicate entries

### ISSUE THREAD

**Issue by faisal-memon** [spiffe/spire#2275] opened 2021-05-11 17:29 UTC
* **Version**: 0.12.1
* **Platform**: Docker Desktop on MacOS
* **Subsystem**: Server and k8s-workload-registrar

While testing with two k8s-workload-registrar's, I noticed duplicate entries were created:

```
$ kubectl exec spire-server-0  -n spire -c spire-server -- ./bin/spire-server entry show
Found 11 entries
Entry ID         : 9ae11a1d-2d36-449a-a869-6fa57b599fbb
SPIFFE ID        : spiffe://example.org/k8s-workload-registrar/nginx-mesh/node/docker-desktop
Parent ID        : spiffe://example.org/spire/server
Revision         : 1
TTL              : default
Selector         : k8s_psat:agent_node_uid:e21842cd-9924-41c4-b9ad-0e577d538c70
Selector         : k8s_psat:cluster:nginx-mesh

Entry ID         : 55561c3d-b6d2-434a-93cd-a3591c5a72ec
SPIFFE ID        : spiffe://example.org/k8s-workload-registrar/nginx-mesh/node/docker-desktop
Parent ID        : spiffe://example.org/spire/server
Revision         : 1
TTL              : default
Selector         : k8s_psat:agent_node_uid:e21842cd-9924-41c4-b9ad-0e577d538c70
Selector         : k8s_psat:cluster:nginx-mesh
```

**Comment by rturner3** [comment] 2023-05-01 19:21
Closing as duplicate of #3467.

**Closed by rturner3** 2023-05-01 19:21 UTC
