### ISSUE TITLE
Release 0.11.1

### ISSUE THREAD

**Issue by APTy** [spiffe/spire#1844] opened 2020-09-17 18:56 UTC
Following the [Release Procedures](https://github.com/spiffe/spire/blob/master/MAINTAINERS.md#releasing):

Commit: 3655ed13f3ceefb26dba8a6bb2fb85e4a5f15225

**Comment by APTy** [comment] 2020-09-24 19:00
We're going to wait on this release until a fix is merged for a breakage in the attestor APIs introduced in v0.11.0. Will follow-up with more info

**Comment by evan2645** [comment] 2020-09-24 20:01
https://github.com/spiffe/spire/pull/1797 has since been merged so I think that means we'll need to create a release branch?

**Comment by azdagron** [comment] 2020-09-24 20:04
Yup. The regression has been fixed in #1863, which was just merged.

**Comment by APTy** [comment] 2020-09-24 23:13
Just created the [v0.11.1](https://github.com/spiffe/spire/tree/v0.11.1) branch, which branches at 3655ed1 and cherry-picks 0ea85f25. I'll also cherry-pick the changelog commit once that is merged.

**Comment by APTy** [comment] 2020-09-30 17:16
Included a few more changes and renamed the branch to [v0.11](https://github.com/spiffe/spire/tree/v0.11). Releasing shortly

**Closed** 2020-09-30 19:21 UTC
