### ISSUE TITLE
k8s selector name are not validated

### ISSUE THREAD

**Issue by sury-gh** [spiffe/spire#1569] opened 2020-05-19 21:39 UTC
* **Version**:  spire-0.10.0
* **Platform**: Linux mytest1 4.19.107 #1 SMP Mon May 11 14:51:04 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**: spire-server

I created a entry for a k8s workload and incorrectly provided the selector name as **k8s:pod_name** instead of **k8s:pod-name** e.g:

`kubectl exec -n spire spire-server-0 --   /opt/spire/bin/spire-server entry create -spiffeID spiffe://example.org/ns/default/sa/default/mytest1 -parentID spiffe://example.org/ns/spire/sa/spire-agent  -selector k8s:ns:default  -selector k8s:sa:default -selector k8s:pod_name:mytest1`

The selector name could be validated and error message shown instead of accepting incorrect selector:

$ ./spire-server entry show
```
Entry ID        : 3216e3ff-76e4-433c-b30a-1a5b84438d1d
SPIFFE ID     : spiffe://example.org/ns/default/sa/default/mytest1
Parent ID     : spiffe://example.org/ns/spire/sa/spire-agent
TTL              : 3600
Selector      : k8s:ns:default
Selector      : k8s:pod-name:mytest1
Selector      : k8s:sa:default

Entry ID       : 73ce3d13-461b-4215-8842-f1e3292266e6
SPIFFE ID    : spiffe://example.org/ns/default/sa/default/mytest1
Parent ID     : spiffe://example.org/ns/spire/sa/spire-agent
TTL              : 3600
Selector      : k8s:ns:default
Selector      : k8s:pod_name:mytest1
Selector      : k8s:sa:default
```

**Comment by amartinezfayo** [comment] 2020-07-30 20:46
Although I understand that this kind of validation would be something desirable, the current implementation makes this something very difficult to achieve. There is no easy way to query for all the available selectors that can be handled by the registered attestor plugins.
I think that we can start by doing some basic validation of well-formed selectors, like pointed in #1314.

**Comment by radoslav-tomov** [comment] 2021-11-12 10:09
@amartinezfayo We need to have validation on a higher level, as miss-configuration is reality. Example I came across - one can create a Node entry, which uses the `gcp_iit` plugin and add 2 different `gcp_iit:project-id` selectors.

**Comment by evan2645** [comment] 2022-10-11 19:49
This is a known issue, and unfortunately as @amartinezfayo points out, the problem is kind of core to the way that selectors work. Plugins can emit any selector they want, and core has no idea what may be emitted in advance. On top of that, validation needs to occur at the server only, and not at the agent which is where these plugins are loaded.

We've looked at this several times and have never found a good answer. In the absence of one, we're going to go ahead and close this out, though we'd still be happy to have a proposal that solves this problem well. Thank you for opening this issue @radoslav-tomov

**Closed by evan2645** 2022-10-11 19:49 UTC
