### ISSUE TITLE
Server and agent should detect unknown config options

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1101] opened 2019-09-04 18:24 UTC
The current behavior of both server and agent is to ignore configurables that we don't know about (i.e. aren't defined in our respective config structs). This causes some friction for a variety of misconfiguration cases:
* A typo in config key name
* Misplaced directives (e.g. a plugin defined in the server configuration block)
* Attempting to use a new feature against an old version

In these cases, SPIRE can boot normally and does not give any indication that something is wrong. Users are then surprised when they don't see the behavior they expect.

Both server and agent should detect if unknown configuration parameters are set, and either warn or refuse to start. The catalog and telemetry subsystems should be updated to have this behavior as well for their respective config blocks. I think the former may already have some of this behavior.

Correctness of plugin_data will need to be handled separately and is out of scope for this issue.

**Comment by ryysud** [comment] 2019-12-03 04:52
Can this issue be closed because it was fixed by #1289?

**Comment by evan2645** [comment] 2019-12-06 23:46
Hello @ryysud, thank you so much for picking this up!

I have been looking at the changes from #1289 for a couple days now, and noticed that there seems to be a bug in the HCL unused keys feature. I left a small note about the issue here: https://github.com/hashicorp/hcl/issues/322#issuecomment-561919807

The end result is that we provide a spurious warning even if the config is valid. Any time someone uses the
```
foo "bar" {
   ...
}
```
shorthand, this will be the case. This shorthand syntax can be used for both slices and maps.

Looking at the comments on the HCL issue above, it seems that we will need to make a move to HCL 2 at some point. That change is likely to be non-trivial. I discussed it briefly with @azdagron and we both felt that there is ample opportunity for a change in behavior to sneak in unnoticed. For that reason, we should probably be careful when doing so, and should also probably align the change with a ".0" release.

We don't want to lose the progress we've made already here though, and there is still a lot of value in providing this protection/detection wherever we can... so, instead of backing the change out entirely, I think we will leave the detection enabled for any/all config blocks that don't have a slice or map element which may use the shorthand syntax.

In light of all this, I think we should probably keep this issue open until all config sections can benefit from this detection. I will open a new issue to get us upgraded to HCL 2.

**Comment by ryysud** [comment] 2019-12-08 07:40
> I have been looking at the changes from #1289 for a couple days now, and noticed that there seems to be a bug in the HCL unused keys feature. I left a small note about the issue here: hashicorp/hcl#322 (comment)

Oh sorry... I didn't notice the bug...

> In light of all this, I think we should probably keep this issue open until all config sections can benefit from this detection. I will open a new issue to get us upgraded to HCL 2.

I understood the procedure for closing this issue.
Thank you for handling the problems caused by my PR.

**Comment by elinesterov** [comment] 2020-06-23 17:05
I want to add another use-case/scenario here so we can consider different points of view. I understand the challenges of misconfiguration, and we should definitely have validation for incorrect configuration options. However, if we deprecate unknown options completely through logic that does not allow the start server/agent if the "unknown" option is detected, then it will be problematic to extend the client or server.
Currently, there are two few ways to extend SPIRE components:
1) Commit to feature to open source project
2) Apply patches to open source code
3) Wrap open source code `c := cli.CLI{}`

The first one does work only for features that will be useful for the majority of users. So if your company has some specifics (e.g., you are using some exotic/company-specific logging/monitoring system or anything else, then this way is not for you. What you can use is a second or third option.
The second option works, fine but you need to fix your patches quite often since opens source code changes as well.
The third option, I believe, will be used by the majority of users. However, if you want to add some configuration options for your code and keep them in the same file ( so you don't end up with two config files for agent or server - one for OSS code and another for your internal systems) with the current approach at this point, you'll get a warning via `l.Warnf("Detected unknown top-level config options: %q; this will be fatal in a future release.", c.UnusedKeys)`.

So what we can do about it:
Make it easier for the community and new users not to make configuration mistakes seems a very reasonable idea, but we should allow more flexibility and extensibility.  The short term solution I see is to add another option to skip the warning/config check. In the long term, we should think about making configuration files extendable (which might come with other extendability improvements).

**Comment by azdagron** [comment] 2020-07-02 13:50
I'll just mention that extending the server/agent via bring-your-own-main and using `cli.CLI` has just superficial support. There is a lot we could do to make SPIRE "embeddable" if that is a use case that we want to support. The current CLI packages are far from ideal for that sort of thing.

**Comment by azdagron** [comment] 2020-07-08 15:56
I've just opened up #1714 which I think has a good compromise. The `cli.CLI` struct gains a new `AllowUnknownConfig` bool. This allows folks extending SPIRE via `cli.CLI` to opt out without adding an extra flag.

**Closed** 2020-07-08 21:01 UTC
Labels: area/user experience
