### ISSUE TITLE
Generate workload certificates based on intermediate CA. 

### ISSUE THREAD

**Issue by trilokgm** [spiffe/spire#638] opened 2018-11-15 06:44 UTC
When workload calls the workload API, the certificate bundle should have 
a. SVID + Intermediate (the chain) 
b. Root CAs belonging to the Upstream SPIRE server (the bundle) 

Detail design document to be published soon.

**Comment by evan2645** [comment] 2018-11-16 00:12
Is this a duplicate of #637 or is it different?

**Comment by deepak-vij** [comment] 2018-11-16 18:03
I think so too, as Evan mentioned that Workload API has been refactored now for delivering the correct intermediate trust chain. Earlier, all the certificates (upstream root + all intermediates) were lumped into a single bundle instead of serving up intermediate certificates appropriately as part of a chain.

@trlokgm, please verify and close this issue if it is duplicate. Thanks.

**Closed** 2018-11-27 21:13 UTC
