### ISSUE TITLE
reduce data transmission load for signing and fetchReg API's

### ISSUE THREAD

**Issue by ryancnelson** [spiffe/spire#1626] opened 2020-06-08 20:29 UTC
during a discussion with a Scytale customer, and improvement was suggested:

Split FetchX509 into Signing and FetchReg APIs. 

reasoning: Signings are only sometimes needed, and syncing registrations is a very expensive operation.

1. An endpoint should have one express, clear purpose.
2. Having levers to adjust signing sync vs registration sync will aid scalability.

@ryancnelson filing this on behalf of the customer so the idea isn't lost, but it's not my idea.

**Comment by azdagron** [comment] 2020-06-08 22:33
I'd like to point out that signing is already only done when needed. In other words, the cadence of signing X509-SVIDs is a consequence of the SVID TTLs, and only loosely related to the registration sync interval, as the the check for expiration is done after fetching the latest registration.

To visualize, `R` is a registration sync, `S` is a signing request. Both `R` and `S` have the same authorization cost. Here is what the agent would do when coming up (where the incrementing numbers represent a  sync interval). Let's consider a 1m TTL and a 5 second sync interval.

1: `R`, `S` (gets the initial X509-SVID signed)
2: `R`
3: `R`
...
6: `R`, `S` (renews the X509-SVID at the half way point, i.e. 30s)
7: `R`
8: `R`
...
12: `R`, `S` (renews the X509-SVID at the half way point)

So there isn't really a "signing" interval that could be tweaked independently...

That being said, the APIs to fetch entries and sign SVIDs have already been separated into distinct, single purpose APIs in the API refactor (development under way).

**Comment by azdagron** [comment] 2020-06-11 23:12
I'm closing this as a duplicate of #1361, which covers a superset of this request.

**Closed by azdagron** 2020-06-11 23:12 UTC
