### ISSUE TITLE
ServerCA HSM plugin

### ISSUE THREAD

**Issue by APTy** [spiffe/spire#525] opened 2018-07-06 21:33 UTC
Following up on some slack conversations with @evan2645 and @dkiser

**Problem Statement**
As a SPIRE server operator, I should be able to configure my server to use a key that lives in an HSM, so that I can sign CSRs without exposing my private key material.

The certificate for this key would be long-lived and live in the HSM, or simply live on the filesystem.

**Solution**
Create a ServerCA plugin that can speak HSM for the purpose of signing and generating CSRs, as well as loading/fetching its own certificate.

To pair with this, we can make one of two changes:
1. Make UpstreamCA an optional step in the ca/manager logic (probably the correct way); or
2. Create an UpstreamCA that always returns the same static certificate on calls to `SubmitCSR`. The private key associated with this certificate is the one that lives in the HSM. (requires no change to ca/manager logic, but feels hacky)

**Comment by evan2645** [comment] 2018-07-06 21:44
Thanks for filing this @APTy 

> Create a ServerCA plugin that can speak HSM for the purpose of signing and generating CSRs, as well as loading/fetching its own certificate.

Would this be PKCS11? Or something more geared toward a specific HSM? If the former, I imagine it would be useful in a bunch of situations, we may be able to get away with something that's PKCS11-generic-y

> To pair with this, we can make one of two changes

I definitely like number 1, but it feels like that might be a separate issue/piece of work? With an HSM-compat ServerCA plugin, we would first call `GenerateCsr`, which in turn can trigger key generation on the HSM, and create a CSR using the generated key... We can still call `LoadCertificate` then with the cert that was signed by upstream, and the key should still be retained by HSM. Perhaps the certificate is stored on disk somewhere? I guess my point here is that creating an HSM-based ServerCA plugin doesn't necessarily _mandate_ changes in the UpstreamCA flow (unless I am missing something?). That being said, I do think we need the ability to disable UpstreamCA flow.

**Comment by APTy** [comment] 2018-07-09 19:24
Will plan for something that revolves heavily around PKCS#11.

Let's start with that, and then we can pull out the UpstreamCA changes into a separate issue.

**Comment by evan2645** [comment] 2018-07-09 22:52
Sounds great.

Please see #526 which was just merged.

@azdagron would you mind summarizing the upcoming JWT changes here as they relate to ServerCA interface? Not sure if you have spoken to @APTy about it yet, just want to make sure you two don't conflict too badly

**Comment by azdagron** [comment] 2018-07-09 23:05
Sure thing. The ServerCA interface is gaining an additional method, `SignJwtSvid`, which takes in a some parameters and returns a signed JWT-A-SVID. In addition, the `SignCsr` method is being renamed to `SignX509SvidCsr`.

The current memory plugin implements the functionality by signing its own JWT signing certificate. The intermediate signed by the upstream CA is used to sign the JWT signing certificate.

**Comment by evan2645** [comment] 2018-08-07 20:57
To follow up here, we have [merged changes](https://github.com/spiffe/spire/pull/539) into master that:
1. Deprecate ServerCA plugin type in favor of a new KeyManager type that gives a simplified, lower-level API which does not concern itself with X.509
1. Makes UpstreamCA plugin optional

Would be great to know if the [defined interface](https://github.com/spiffe/spire/blob/master/proto/server/keymanager/keymanager.proto) is suitable for your use.

**Comment by omerlh** [comment] 2019-05-19 13:24
I looked on the protocol, the main challenge here is the method to get the private key. The main benefit of using HSM is to ensure that the private key cannot be extracted. Is that something that was discussed?

**Comment by evan2645** [comment] 2019-05-20 08:47
@omerlh the [server proto](https://github.com/spiffe/spire/blob/master/proto/spire/server/keymanager/keymanager.proto) does not require the private key to be returned and is designed for use with an HSM.

The [agent proto](https://github.com/spiffe/spire/blob/master/proto/spire/agent/keymanager/keymanager.proto) does, however, require that the private key be returned. This is because it was designed for use with a TPM where private keys are commonly wrapped rather than stored behind PKCS#11, and facilitates ease of use in the agent with TLS. There is currently an [open issue](https://github.com/spiffe/spire/issues/670) for moving the agent to an interface that will support PKCS#11.

**Comment by evan2645** [comment] 2021-04-14 20:19
This has long been solved. The upstream plugin is optional, and the server's keymanager plugin interface has been designed to support HSM interaction. Closing this as fixed

**Closed by evan2645** 2021-04-14 20:19 UTC

**Comment by udf2457** [comment] 2023-03-31 11:41
@evan2645 PKCS11 has "long been solved" but I can't see any reference to it either in the docs (https://spiffe.io/docs/latest/deploying/spire_server/) or a simple search of the github repo ?  What happened ?

**Comment by evan2645** [comment] 2023-03-31 15:57
Hi @udf2457 - this issue was not about supporting PKCS#11 directly, instead it was about ensuring that SPIRE Server had a pluggable interface that is compatible with PKCS#11. That was done a long time ago, the conclusion was described in this comment: https://github.com/spiffe/spire/issues/525#issuecomment-411200147

If you have a PKCS#11 hardware device, it should be trivial to write a plugin against it using the KeyManager interface that was introduced as part of this work. The plugin SDK has [a template](https://github.com/spiffe/spire-plugin-sdk/blob/main/templates/server/keymanager/keymanager.go) you can use
