### ISSUE TITLE
Spire server expose bundle in PEM format

### ISSUE THREAD

**Issue by Kaizhe** [spiffe/spire#2737] opened 2022-02-03 22:34 UTC
This is more of a feature request. Expose bundle in PEM format so that agent can be consumed directly using `trust_bundle_url`. More in the conversation:  https://spiffe.slack.com/archives/C7XDP01HB/p1643922493083769

* **Version**: 
* 1.1.3
* **Platform**: 
* Ubuntu
* **Subsystem**:

**Comment by dfeldman** [comment] 2022-02-03 22:38
The idea here is that the agent could get the initial trust bundle from the SPIRE server itself, over an HTTPS connection. The SPIRE server already serves these using an ACME cert for federation purposes, but this is in JWKS format, not in PEM format which is required for agents. The simplest thing to do here is allow the trust_bundle_url configurable to take a URL for a JWKS file instead of just a PEM file. Then the user can configure the SPIRE server to have a federation bundle endpoint, which will also do double duty as an initial trust bundle source.

**Comment by Kaizhe** [comment] 2022-02-04 00:10
> The idea here is that the agent could get the initial trust bundle from the SPIRE server itself, over an HTTPS connection. The SPIRE server already serves these using an ACME cert for federation purposes, but this is in JWKS format, not in PEM format which is required for agents.
> 
> The simplest thing to do here is allow the trust_bundle_url configurable to take a URL for a JWKS file instead of just a PEM file. Then the user can configure the SPIRE server to have a federation bundle endpoint, which will also do double duty as an initial trust bundle source for agents.
> 
> One downside is that then configuring federation in the server would be necessary for a purpose that has nothing to do with federation...

Thanks @dfeldman , I think what you said is a more robust design!

**Comment by evan2645** [comment] 2023-02-17 21:23
I think this is a duplicate of https://github.com/spiffe/spire/pull/3753 , which has since been completed. Please let us know if we missed anything!

**Closed by evan2645** 2023-02-17 21:23 UTC
